results/urls.py
from django.urls import path
from .views import *

app_name = 'results'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('lga-results/', LGAResultListView.as_view(), name='lga-results'),
    path('summed-results/<slug:name>/', LGATotalResult.as_view(), name='summed-results'),
    path('pu-results/', PUResultListView.as_view(), name='pu-results'),
]

votingsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('results.urls', namespace='results')),
]

agents/models.py
from django.db import models
from django.contrib.auth.models import User


class Agent(models.Model):
    user = models.OneToOneField(User, related_name='agent', on_delete=models.CASCADE)
    phone = models.CharField(max_length=13)    

    def __str__(self):
        return f'{self.firstname, self.lastname}'
    

party/models.py
from django.db import models


class Party(models.Model):
    name = models.CharField(max_length=11)

    def __str__(self):
        return f'{self.name}'
    

results/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count, Sum
from django.utils.timezone import now
from states.models import LGA, PollingUnit
from party.models import Party


class AnnouncedLGAResult(models.Model):
    lga_name = models.ForeignKey(LGA, related_name='lga_results', on_delete=models.CASCADE)
    party_abbr = models.ForeignKey(Party, related_name='lga_party_score', on_delete=models.CASCADE)
    agent = models.ForeignKey(User, on_delete=models.CASCADE)
    party_score = models.PositiveIntegerField()
    date = models.DateTimeField(default=now)

    def __str__(self):
        return f'{self.lga_name}, {self.party_abbr} Score'
    


class AnnouncedPUResult(models.Model):
    pu_id = models.ForeignKey(PollingUnit, related_name='pu_results', on_delete=models.CASCADE)
    party_abbr = models.ForeignKey(Party, related_name='pu_party_score', on_delete=models.CASCADE)
    agent = models.ForeignKey(User, on_delete=models.CASCADE)
    party_score = models.PositiveIntegerField()
    date = models.DateTimeField(default=now)

    def total_result(self):
        results = AnnouncedPUResult.objects.aggregate(Sum('party_score'))
        return results

    def __str__(self):
        return f'{self.pu_id}, {self.party_abbr} Score'
    

states/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from . import choices

class State(models.Model):
    name = models.CharField(max_length=50, choices=choices.states, default='Abia')

    def __str__(self):
        return f'{self.name}'


class LGA(models.Model):
    name = models.CharField(max_length=50)
    state = models.ForeignKey(State, related_name='states', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("results:summed-results", kwargs={"name": self.name})
    

    def __str__(self):
        return f'{self.name}'
    

class Ward(models.Model):
    name = models.CharField(max_length=50)
    lga = models.ForeignKey(LGA, related_name='lgas', on_delete=models.CASCADE)
    state = models.ForeignKey(State, related_name='ward_states', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'


class PollingUnit(models.Model):
    name = models.CharField(max_length=50)
    lga = models.ForeignKey(LGA, related_name='pu_lgas', on_delete=models.CASCADE)
    state = models.ForeignKey(State, related_name='pu_states', on_delete=models.CASCADE)
    agent = models.ForeignKey(User, related_name='agents', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

agents/views.py
from django.shortcuts import render

# Create your views here.

party/views.py
from django.shortcuts import render

# Create your views here.

results/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView

from states.models import LGA, PollingUnit
from .models import AnnouncedLGAResult, AnnouncedPUResult


class IndexView(TemplateView):
    template_name = 'results/index.html'


class LGAResultListView(ListView):
    model = AnnouncedLGAResult
    template_name = 'results/lga_results.html'
    ordering = '-date'


    def get_context_data(self, *, object_list=None, **kwargs):        
        results = AnnouncedLGAResult.objects.all()
        context = {
            'title': 'LGA Results',
            'results': results,            
        }
        return context


class LGATotalResult(DetailView):
    model = PollingUnit
    template_name = 'results/summed_results.html'

    def get_context_data(self, **kwargs):
        pu_result = get_object_or_404(PollingUnit, self.kwargs.get('name'))        
        context = {
            'result': pu_result
        }
        return context
    


class PUResultListView(ListView):
    model = AnnouncedPUResult
    template_name = 'results/pu_results.html'
    ordering = '-date'

    def get_context_data(self, *, object_list=None, **kwargs):
        results = AnnouncedPUResult.objects.all()        
        context = {
            'title': 'PU Results',
            'results': results
        }
        return context

states/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    {% if title %}
        <title>Voting System | {{ title }}</title>
    {% else %}
        <title>Voting System | {% block title %}{% endblock %}</title>
    {% endif %}
</head>
<body>

{% include 'partials/_navbar.html' %}

{% block content %}
{% endblock %}


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

templates/partials/_navbar.html
{% load static %}

<!-- Navbar -->

<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top" id="home-navbar">
    <a href="{% url 'results:index' %}" class="navbar-brand">
        <img src="{% static 'img/favicon.jpg' %}" alt="favicon" class="rounded-circle" width="50" height="50">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav grid-navbar">
            <li {% if '/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                <a href="{% url 'results:index' %}" class="nav-link">
                    <i class="fas fa-home"></i> Home
                </a>
            </li>
            <li {% if 'pu-results' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                <a href="{% url 'results:pu-results' %}" class="nav-link">
                    <i class="fas fa-newspaper"></i> Polling Unit Results
                </a>
            </li>
            <li {% if 'lga-results' in request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                <a href="{% url 'results:lga-results' %}" class="nav-link">
                    <i class="fas fa-newspaper"></i> LGA Results
                </a>
            </li>        
        </ul>
    </div>
</nav>

templates/results/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <a href="{% url 'results:pu-results' %}" class="text-decoration-none">
                    Polling Unit Results
                </a>
            </div>
            <div class="col">
                <a href="{% url 'results:lga-results' %}" class="text-decoration-none">
                    LGA Results
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/results/lga_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        {% for result in results  %}
            <div class="card">
                <div class="card-header">                    
                    <h3 class="text-center">{{ result.party_abbr }}</h3>
                </div>
                <div class="card-body">                    
                    <p class="text-center font-weight-bolder">
                        LGA: <a href="{{ result.get_absolute_url }}">{{ result.lga_name }}</a>                
                    </p>
                    <p class="text-center font-weight-bolder">
                        Score: {{ result.party_score }}            
                    </p>
                </div>
                <div class="card-footer">                    
                    <p>
                        endorsed by: {{ result.lga_results.pu_lags.pu_results.total_result }}
                    </p>
                </div>
            </div>            
        {% endfor %}        
    </div>
{% endblock %}

templates/results/pu_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        {% for result in results  %}
            <div class="card">
                <div class="card-header">                    
                    <h3 class="text-center">{{ result.party_abbr }}</h3>
                </div>
                <div class="card-body">
                    <p class="text-center font-weight-bolder">
                        Polling unit: {{ result.pu_id }}                
                    </p>
                    <p class="text-center font-weight-bolder">
                        Score: {{ result.party_score }}            
                    </p>
                </div>
                <div class="card-footer">                    
                    <p class="font-weight-bolder">
                        endorsed by: {{ result.agent }}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/results/summed_results.html
{% extends 'base.html' %}

{% block content %}
    <p>
        {{ result.pu_results.total_result }}
    </p>
{% endblock %}